/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author zhusheng
 */
public class uiEditHall extends javax.swing.JFrame {
    private Scheduler scheduler;
    /**
     * Creates new form uiEditHall
     */
    public uiEditHall(){
        
    }
    public uiEditHall(Scheduler scheduler) {
        this.scheduler = scheduler;
        initComponents();
        ArrayList<Hall> halls = FileOperations.read("halls.txt", Hall.class);
        for(Hall hall : halls) {
            comboHallID.addItem(hall.getHallID());
        }
        comboHallID.setSelectedIndex(-1);
        lblHallType.setVisible(Boolean.FALSE);
        lblHallStatus.setVisible(Boolean.FALSE);
        comboHallStatus.setVisible(Boolean.FALSE);
        comboHallType.setVisible(Boolean.FALSE);
        btnSave.setVisible(Boolean.FALSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEditHall = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboHallID = new javax.swing.JComboBox<>();
        lblHallType = new javax.swing.JLabel();
        comboHallType = new javax.swing.JComboBox<>();
        lblHallStatus = new javax.swing.JLabel();
        comboHallStatus = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        lblRemarks = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlEditHall.setBackground(new java.awt.Color(255, 255, 255));
        pnlEditHall.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Choose Hall:");

        comboHallID.setBackground(new java.awt.Color(255, 255, 255));
        comboHallID.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        comboHallID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboHallIDActionPerformed(evt);
            }
        });

        lblHallType.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lblHallType.setForeground(new java.awt.Color(0, 0, 0));
        lblHallType.setText("Hall Type");

        comboHallType.setBackground(new java.awt.Color(255, 255, 255));
        comboHallType.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        comboHallType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auditorium", "Banquet Hall", "Meeting Room" }));
        comboHallType.setSelectedIndex(-1);

        lblHallStatus.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lblHallStatus.setForeground(new java.awt.Color(0, 0, 0));
        lblHallStatus.setText("Hall Status");

        comboHallStatus.setBackground(new java.awt.Color(255, 255, 255));
        comboHallStatus.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        comboHallStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        comboHallStatus.setSelectedIndex(-1);

        btnSave.setBackground(new java.awt.Color(153, 204, 255));
        btnSave.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 0, 0));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblRemarks.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lblRemarks.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlEditHallLayout = new javax.swing.GroupLayout(pnlEditHall);
        pnlEditHall.setLayout(pnlEditHallLayout);
        pnlEditHallLayout.setHorizontalGroup(
            pnlEditHallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditHallLayout.createSequentialGroup()
                .addGroup(pnlEditHallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditHallLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pnlEditHallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlEditHallLayout.createSequentialGroup()
                                .addComponent(lblHallStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboHallStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEditHallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditHallLayout.createSequentialGroup()
                                    .addComponent(lblHallType, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboHallType, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlEditHallLayout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboHallID, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblRemarks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlEditHallLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnlEditHallLayout.setVerticalGroup(
            pnlEditHallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditHallLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnlEditHallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboHallID, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditHallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHallType, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboHallType, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEditHallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHallStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboHallStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(lblRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEditHall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEditHall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(comboHallType.getSelectedIndex()==-1 || comboHallStatus.getSelectedIndex()==-1)
        {
            lblRemarks.setText("Hall type and status cannot be empty.");
        }
        else{
            String hallID = String.valueOf(comboHallID.getSelectedItem());
            try {
                scheduler.editHall(hallID, comboHallType.getSelectedIndex(),comboHallType.getSelectedIndex());
                lblRemarks.setText("Hall Updated");
            } catch (IOException ex) {
                Logger.getLogger(uiEditHall.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void comboHallIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboHallIDActionPerformed
        lblHallType.setVisible(Boolean.TRUE);
        lblHallStatus.setVisible(Boolean.TRUE);
        comboHallStatus.setVisible(Boolean.TRUE);
        comboHallType.setVisible(Boolean.TRUE);
        btnSave.setVisible(Boolean.TRUE);
    }//GEN-LAST:event_comboHallIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uiEditHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uiEditHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uiEditHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uiEditHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uiEditHall().setVisible(true);
            }
        });
    }
    public JPanel getPanel(){
        return pnlEditHall;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboHallID;
    private javax.swing.JComboBox<String> comboHallStatus;
    private javax.swing.JComboBox<String> comboHallType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHallStatus;
    private javax.swing.JLabel lblHallType;
    private javax.swing.JLabel lblRemarks;
    private javax.swing.JPanel pnlEditHall;
    // End of variables declaration//GEN-END:variables
}
